{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\",fstype=\"ext4\"} * 100) / node_filesystem_size_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\",fstype=\"ext4\"})"
    }
   ]
  },
  {
   "title": "CPU util",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "LA/1"
    },
    {
     "expr": "avg(node_load5) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "LA/5"
    },
    {
     "expr": "avg(node_load15) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "LA/15"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1073741824",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes / 1073741824",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1073741824",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\",fstype=\"ext4\"} * 100) / node_filesystem_size_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\",fstype=\"ext4\"})"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load1) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "LA/1"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1073741824",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes / 1073741824",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1073741824",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load5) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "LA/5"
    }
   ]
  },
  {
   "title": "CPU util",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load15) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "LA/15"
    }
   ]
  }
 ]
}