---
clickhouse:
  hosts:
    clickhouse-01:
        ansible_connection: ssh
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_host: 84.252.129.6
vector:
  hosts: 
    vector-01:
        ansible_connection: ssh
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_host: 62.84.116.21
lighthouse:
  hosts: 
    lighthouse:
        ansible_connection: ssh
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_host: 84.201.132.160

