---
- name: Install vector
  hosts: vector
  roles:
    - vector
      
- name: Install lighthouse
  hosts: lighthouse
  roles: 
    - lighthouse

- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse