---
# tasks file for vector
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
- name: Install vector packages
  become: true
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}.rpm
  notify: Start vector service
- name: Replace vector.yaml
  become: true
  template:
    src: templates/vector.yaml
    dest: /etc/vector/vector.yaml
  notify: Restart vector service
- name: Flush handlers
  meta: flush_handlers