---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.123.29
    nexus-01:
      ansible_host: 158.160.109.196
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection: ssh
    ansible_user: cherepanov
    ansible_ssh_private_key_file: /home/ntb/.ssh/id_ed25519.pub
